// <auto-generated />
namespace Lab3.Migrations.Country
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FixingCode : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixingCode));
        
        string IMigrationMetadata.Id
        {
            get { return "201702011717448_FixingCode"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
